// Generated by test/session-host-conformance/generate.ts. Do not edit.
// Zig 0.15.2 compilation is provisioned by WP1; WP0 intentionally does not install it.

pub const protocol_major: u8 = 1;
pub const protocol_minor: u8 = 0;
pub const protocol_min_minor: u8 = 0;
pub const protocol_max_minor: u8 = 0;
pub const frame_header_bytes: usize = 32;
pub const frame_magic = "HVT1";
pub const frame_optional_type_bit: u16 = 0x8000;
pub const frame_allowed_flags: u16 = 0x000f;

pub const frame_flag = struct {
    pub const response: u16 = 0x0001;
    pub const final: u16 = 0x0002;
    pub const error_flag: u16 = 0x0004;
    pub const content_sensitive: u16 = 0x0008;
};

pub const frame_type = struct {
    pub const hello: u16 = 0x0001;
    pub const welcome: u16 = 0x0002;
    pub const @"error": u16 = 0x0003;
    pub const ping: u16 = 0x0004;
    pub const pong: u16 = 0x0005;
    pub const create_begin: u16 = 0x0100;
    pub const create_input: u16 = 0x0101;
    pub const create_commit: u16 = 0x0102;
    pub const created: u16 = 0x0103;
    pub const list: u16 = 0x0110;
    pub const listed: u16 = 0x0111;
    pub const inspect: u16 = 0x0112;
    pub const inspected: u16 = 0x0113;
    pub const terminate: u16 = 0x0114;
    pub const terminated: u16 = 0x0115;
    pub const visibility_renew: u16 = 0x0116;
    pub const renewed: u16 = 0x0117;
    pub const input_orphan_discard: u16 = 0x0118;
    pub const orphan_discarded: u16 = 0x0119;
    pub const attach_request: u16 = 0x0200;
    pub const attach_grant: u16 = 0x0201;
    pub const host_attach: u16 = 0x0202;
    pub const snapshot_begin: u16 = 0x0203;
    pub const snapshot_bytes: u16 = 0x0204;
    pub const output: u16 = 0x0205;
    pub const applied: u16 = 0x0206;
    pub const resize: u16 = 0x0207;
    pub const detach: u16 = 0x0208;
    pub const event: u16 = 0x0209;
    pub const claim_acquire: u16 = 0x0300;
    pub const claim_result: u16 = 0x0301;
    pub const human_input: u16 = 0x0302;
    pub const claim_release: u16 = 0x0303;
    pub const gesture_input: u16 = 0x0304;
    pub const input_submit: u16 = 0x0305;
    pub const automation_begin: u16 = 0x0310;
    pub const automation_chunk: u16 = 0x0311;
    pub const automation_commit: u16 = 0x0312;
    pub const automation_result: u16 = 0x0313;
    pub const automation_cancel: u16 = 0x0314;
    pub const host_register: u16 = 0x0400;
    pub const host_adopt: u16 = 0x0401;
    pub const grant_register: u16 = 0x0402;
};

pub const wire_schema = struct {
    pub const hello_payload = "helloPayload";
    pub const welcome_payload = "welcomePayload";
    pub const error_payload = "errorPayload";
    pub const ping_pong_payload = "pingPongPayload";
    pub const host_register_payload = "hostRegisterPayload";
    pub const host_adopt_payload = "hostAdoptPayload";
    pub const grant_register_payload = "grantRegisterPayload";
    pub const host_record_v1 = "hostRecordV1";
    pub const create_begin_payload = "createBeginPayload";
    pub const create_commit_payload = "createCommitPayload";
    pub const created_payload = "createdPayload";
    pub const list_payload = "listPayload";
    pub const listed_payload = "listedPayload";
    pub const inspect_payload = "inspectPayload";
    pub const inspected_payload = "inspectedPayload";
    pub const terminate_payload = "terminatePayload";
    pub const terminated_payload = "terminatedPayload";
    pub const visibility_renew_payload = "visibilityRenewPayload";
    pub const renewed_payload = "renewedPayload";
    pub const orphan_discard_payload = "orphanDiscardPayload";
    pub const orphan_discarded_payload = "orphanDiscardedPayload";
    pub const attach_request_payload = "attachRequestPayload";
    pub const attach_grant_payload = "attachGrantPayload";
    pub const host_attach_payload = "hostAttachPayload";
    pub const claim_acquire_payload = "claimAcquirePayload";
    pub const claim_result_payload = "claimResultPayload";
    pub const input_submit_payload = "inputSubmitPayload";
    pub const resize_payload = "resizePayload";
    pub const applied_payload = "appliedPayload";
    pub const terminal_host_create_request = "terminalHostCreateRequest";
    pub const terminal_host_create_result = "terminalHostCreateResult";
    pub const terminal_host_checkpoint = "terminalHostCheckpoint";
    pub const terminal_host_session_inspection = "terminalHostSessionInspection";
    pub const terminal_host_termination_request = "terminalHostTerminationRequest";
    pub const terminal_host_termination_result = "terminalHostTerminationResult";
    pub const terminal_host_resize_request = "terminalHostResizeRequest";
    pub const terminal_host_resize_receipt = "terminalHostResizeReceipt";
    pub const terminal_host_attach_request = "terminalHostAttachRequest";
    pub const terminal_host_attach_result = "terminalHostAttachResult";
    pub const terminal_host_subscribe_request = "terminalHostSubscribeRequest";
    pub const terminal_host_subscribe_result = "terminalHostSubscribeResult";
    pub const terminal_host_visibility_renewal_request = "terminalHostVisibilityRenewalRequest";
    pub const terminal_host_visibility_renewal_result = "terminalHostVisibilityRenewalResult";
    pub const session_locator = "sessionLocator";
    pub const terminal_geometry = "terminalGeometry";
    pub const session_spec = "sessionSpec";
    pub const session_inspection = "sessionInspection";
    pub const create_result = "createResult";
    pub const capture_request = "captureRequest";
    pub const capture_result = "captureResult";
    pub const attach_request = "attachRequest";
    pub const attach_grant = "attachGrant";
    pub const visibility_request = "visibilityRequest";
    pub const visibility_lease = "visibilityLease";
    pub const resize_result = "resizeResult";
    pub const automated_input_metadata = "automatedInputMetadata";
    pub const input_receipt = "inputReceipt";
    pub const termination_request = "terminationRequest";
    pub const termination_result = "terminationResult";
    pub const session_event = "sessionEvent";
};

pub const wire_error = enum {
    protocol_mismatch,
    unsupported_frame,
    unauthenticated,
    forbidden,
    instance_mismatch,
    generation_mismatch,
    generation_gone,
    not_found,
    not_ready,
    already_exists,
    human_owned,
    human_orphaned,
    input_busy,
    rebase_required,
    snapshot_required,
    checkpoint_unavailable,
    engine_mismatch,
    payload_too_large,
    frame_too_large,
    malformed_frame,
    in_doubt,
    verification_unknown,
    capacity_exceeded,
    resource_exhausted,
    internal,
};

pub const input_state = enum {
    free,
    human_gesture,
    human_owned,
    human_orphaned,
    automation_buffering,
    automation_committed,
    terminating,
    closed,
};

pub const input_evidence = enum {
    buffered,
    committed,
    written,
    provider_observed,
};

pub const ghostty_bridge_event = enum(u8) {
    invalidate = 1,
    title = 2,
    pwd = 3,
    bell = 4,
    clipboard_denied = 5,
    close_request = 6,
};

pub const checkpoint = struct {
    pub const magic = "HVTCP001";
    pub const version: u16 = 1;
    pub const header_bytes: usize = 116;
    pub const flags: u32 = 0;
    pub const engine_build_id_bytes: usize = 32;
    pub const payload_sha256_bytes: usize = 32;
    pub const offset = struct {
        pub const magic: usize = 0;
        pub const version: usize = 8;
        pub const header_bytes: usize = 10;
        pub const flags: usize = 12;
        pub const through_seq: usize = 16;
        pub const created_mono_nanos: usize = 24;
        pub const columns: usize = 32;
        pub const rows: usize = 36;
        pub const cell_width_px: usize = 40;
        pub const cell_height_px: usize = 44;
        pub const engine_build_id: usize = 48;
        pub const payload_length: usize = 80;
        pub const payload_sha256: usize = 84;
    };
    pub const width = struct {
        pub const magic: usize = 8;
        pub const version: usize = 2;
        pub const header_bytes: usize = 2;
        pub const flags: usize = 4;
        pub const through_seq: usize = 8;
        pub const created_mono_nanos: usize = 8;
        pub const columns: usize = 4;
        pub const rows: usize = 4;
        pub const cell_width_px: usize = 4;
        pub const cell_height_px: usize = 4;
        pub const engine_build_id: usize = 32;
        pub const payload_length: usize = 4;
        pub const payload_sha256: usize = 32;
    };
};

pub const limits = struct {
    pub const live_sessions_per_hive_home: usize = 32;
    pub const viewers_per_generation: usize = 4;
    pub const control_json_bytes: usize = 262144;
    pub const input_transaction_bytes: usize = 131072;
    pub const stream_chunk_bytes: usize = 65536;
    pub const automated_message_bytes: usize = 1048576;
    pub const viewer_queue_bytes: usize = 8388608;
    pub const checkpoint_bytes: usize = 67108864;
    pub const terminal_disk_bytes: u64 = 2147483648;
    pub const control_rpc_timeout_ms: u64 = 10000;
    pub const attach_grant_timeout_ms: u64 = 30000;
    pub const visibility_renewal_ms: u64 = 5000;
    pub const visibility_expiry_ms: u64 = 15000;
    pub const connection_ping_interval_ms: u64 = 5000;
    pub const missed_pong_intervals: u8 = 3;
};

// Payloads remain schema-driven; no hand-maintained Zig payload structs live here.
pub const schema_fixture = @embedFile("session-protocol.schema.json");
pub const wire_corpus_fixture = @embedFile("session-protocol-corpus.json");
pub const reducer_corpus_fixture = @embedFile("reducer-parity-corpus.json");
