// Generated by test/session-host-conformance/generate.ts. Do not edit.
// Zig 0.15.2 compilation is provisioned by WP1; WP0 intentionally does not install it.

pub const protocol_major: u8 = 1;
pub const protocol_minor: u8 = 0;
pub const frame_header_bytes: usize = 32;
pub const frame_magic = "HVT1";
pub const frame_allowed_flags: u16 = 0x000f;

pub const frame_type = struct {
    pub const hello: u16 = 0x0001;
    pub const welcome: u16 = 0x0002;
    pub const error: u16 = 0x0003;
    pub const ping: u16 = 0x0004;
    pub const pong: u16 = 0x0005;
    pub const create_begin: u16 = 0x0100;
    pub const create_input: u16 = 0x0101;
    pub const create_commit: u16 = 0x0102;
    pub const created: u16 = 0x0103;
    pub const list: u16 = 0x0110;
    pub const listed: u16 = 0x0111;
    pub const inspect: u16 = 0x0112;
    pub const inspected: u16 = 0x0113;
    pub const terminate: u16 = 0x0114;
    pub const terminated: u16 = 0x0115;
    pub const visibility_renew: u16 = 0x0116;
    pub const renewed: u16 = 0x0117;
    pub const attach_request: u16 = 0x0200;
    pub const attach_grant: u16 = 0x0201;
    pub const host_attach: u16 = 0x0202;
    pub const snapshot_begin: u16 = 0x0203;
    pub const snapshot_bytes: u16 = 0x0204;
    pub const output: u16 = 0x0205;
    pub const applied: u16 = 0x0206;
    pub const resize: u16 = 0x0207;
    pub const detach: u16 = 0x0208;
    pub const event: u16 = 0x0209;
    pub const claim_acquire: u16 = 0x0300;
    pub const claim_result: u16 = 0x0301;
    pub const human_input: u16 = 0x0302;
    pub const claim_release: u16 = 0x0303;
    pub const gesture_input: u16 = 0x0304;
    pub const automation_begin: u16 = 0x0310;
    pub const automation_chunk: u16 = 0x0311;
    pub const automation_commit: u16 = 0x0312;
    pub const automation_result: u16 = 0x0313;
    pub const automation_cancel: u16 = 0x0314;
    pub const host_register: u16 = 0x0400;
    pub const host_adopt: u16 = 0x0401;
    pub const grant_register: u16 = 0x0402;
};

pub const wire_error = enum {
    protocol_mismatch,
    unsupported_frame,
    unauthenticated,
    forbidden,
    instance_mismatch,
    generation_mismatch,
    not_found,
    not_ready,
    already_exists,
    human_owned,
    human_orphaned,
    input_busy,
    rebase_required,
    snapshot_required,
    checkpoint_unavailable,
    engine_mismatch,
    payload_too_large,
    frame_too_large,
    malformed_frame,
    in_doubt,
    verification_unknown,
    capacity_exceeded,
    resource_exhausted,
    internal,
};

pub const input_state = enum {
    free,
    human_gesture,
    human_owned,
    human_orphaned,
    automation_buffering,
    automation_committed,
    terminating,
    closed,
};

pub const input_evidence = enum {
    buffered,
    committed,
    written,
    provider_observed,
};

pub const ghostty_bridge_event = enum(u8) {
    invalidate = 1,
    title = 2,
    pwd = 3,
    bell = 4,
    clipboard_denied = 5,
    close_request = 6,
};

pub const checkpoint = struct {
    pub const magic = "HVTCP001";
    pub const version: u16 = 1;
    pub const header_bytes: usize = 116;
    pub const flags: u32 = 0;
    pub const engine_build_id_bytes: usize = 32;
    pub const payload_sha256_bytes: usize = 32;
};

pub const limits = struct {
    pub const live_sessions_per_hive_home: usize = 32;
    pub const viewers_per_generation: usize = 4;
    pub const control_json_bytes: usize = 262144;
    pub const stream_chunk_bytes: usize = 65536;
    pub const automated_message_bytes: usize = 1048576;
    pub const checkpoint_bytes: usize = 67108864;
    pub const terminal_disk_bytes: u64 = 2147483648;
};

// Payloads remain schema-driven; no hand-maintained Zig payload structs live here.
pub const schema_fixture = @embedFile("session-protocol.schema.json");
pub const wire_corpus_fixture = @embedFile("session-protocol-corpus.json");
pub const reducer_corpus_fixture = @embedFile("reducer-parity-corpus.json");
