// Generated by test/session-host-conformance/generate.ts. Do not edit.
import CryptoKit
import CoreFoundation
import Foundation

enum SessionProtocolGenerated {
    static let protocolMajor: UInt8 = 1
    static let protocolMinor: UInt8 = 0
    static let protocolMinMinor: UInt8 = 0
    static let protocolMaxMinor: UInt8 = 0
    static let headerBytes = 32
    static let optionalTypeBit: UInt16 = 0x8000
    static let magic: [UInt8] = [72, 86, 84, 49]
    static let allowedFlags: UInt16 = 15
    static let controlFrameBytes = 262144
    static let streamFrameBytes = 65536
    static let frameTypes: [String: UInt16] = [
        "HELLO": 0x0001,
        "WELCOME": 0x0002,
        "ERROR": 0x0003,
        "PING": 0x0004,
        "PONG": 0x0005,
        "CREATE_BEGIN": 0x0100,
        "CREATE_INPUT": 0x0101,
        "CREATE_COMMIT": 0x0102,
        "CREATED": 0x0103,
        "LIST": 0x0110,
        "LISTED": 0x0111,
        "INSPECT": 0x0112,
        "INSPECTED": 0x0113,
        "TERMINATE": 0x0114,
        "TERMINATED": 0x0115,
        "VISIBILITY_RENEW": 0x0116,
        "RENEWED": 0x0117,
        "INPUT_ORPHAN_DISCARD": 0x0118,
        "ORPHAN_DISCARDED": 0x0119,
        "ATTACH_REQUEST": 0x0200,
        "ATTACH_GRANT": 0x0201,
        "HOST_ATTACH": 0x0202,
        "SNAPSHOT_BEGIN": 0x0203,
        "SNAPSHOT_BYTES": 0x0204,
        "OUTPUT": 0x0205,
        "APPLIED": 0x0206,
        "RESIZE": 0x0207,
        "DETACH": 0x0208,
        "EVENT": 0x0209,
        "CLAIM_ACQUIRE": 0x0300,
        "CLAIM_RESULT": 0x0301,
        "HUMAN_INPUT": 0x0302,
        "CLAIM_RELEASE": 0x0303,
        "GESTURE_INPUT": 0x0304,
        "INPUT_SUBMIT": 0x0305,
        "AUTOMATION_BEGIN": 0x0310,
        "AUTOMATION_CHUNK": 0x0311,
        "AUTOMATION_COMMIT": 0x0312,
        "AUTOMATION_RESULT": 0x0313,
        "AUTOMATION_CANCEL": 0x0314,
        "HOST_REGISTER": 0x0400,
        "HOST_ADOPT": 0x0401,
        "GRANT_REGISTER": 0x0402
    ]
    static let rawFrameTypes: Set<String> = ["CREATE_INPUT", "SNAPSHOT_BYTES", "OUTPUT", "HUMAN_INPUT", "AUTOMATION_CHUNK"]

    /// HVTCP001 checkpoint envelope (§23 / CHECKPOINT_HEADER).
    enum Checkpoint {
        static let magic = "HVTCP001"
        static let version: UInt16 = 1
        static let headerBytes = 116
        static let flags: UInt32 = 0
        static let engineBuildIdBytes = 32
        static let payloadSha256Bytes = 32
        enum Offset {
            static let magic = 0
            static let version = 8
            static let headerBytes = 10
            static let flags = 12
            static let throughSeq = 16
            static let createdMonoNanos = 24
            static let columns = 32
            static let rows = 36
            static let cellWidthPx = 40
            static let cellHeightPx = 44
            static let engineBuildId = 48
            static let payloadLength = 80
            static let payloadSha256 = 84
        }
        enum Width {
            static let magic = 8
            static let version = 2
            static let headerBytes = 2
            static let flags = 4
            static let throughSeq = 8
            static let createdMonoNanos = 8
            static let columns = 4
            static let rows = 4
            static let cellWidthPx = 4
            static let cellHeightPx = 4
            static let engineBuildId = 32
            static let payloadLength = 4
            static let payloadSha256 = 32
        }
    }
}

enum ContractFailure: Error, CustomStringConvertible {
    case message(String)
    var description: String {
        switch self { case .message(let value): return value }
    }
}

func readJSON(_ path: String) throws -> Any {
    try JSONSerialization.jsonObject(with: Data(contentsOf: URL(fileURLWithPath: path)))
}

func jsonScalar(_ value: Any) throws -> String {
    let data = try JSONSerialization.data(
        withJSONObject: value,
        options: [.withoutEscapingSlashes, .fragmentsAllowed])
    return String(decoding: data, as: UTF8.self)
}

func canonicalJSON(_ value: Any) throws -> String {
    if value is NSNull { return "null" }
    if let number = value as? NSNumber {
        if CFGetTypeID(number) == CFBooleanGetTypeID() {
            return number.boolValue ? "true" : "false"
        }
        return try jsonScalar(number)
    }
    if let string = value as? String { return try jsonScalar(string) }
    if let array = value as? [Any] {
        return "[" + (try array.map(canonicalJSON)).joined(separator: ",") + "]"
    }
    if let object = value as? [String: Any] {
        let keys = object.keys.sorted {
            $0.utf16.lexicographicallyPrecedes($1.utf16)
        }
        let fields = try keys.map { key in
            try jsonScalar(key) + ":" + canonicalJSON(object[key]!)
        }
        return "{" + fields.joined(separator: ",") + "}"
    }
    throw ContractFailure.message("unsupported JSON value")
}

func isBoolean(_ value: Any) -> Bool {
    guard let number = value as? NSNumber else { return false }
    return CFGetTypeID(number) == CFBooleanGetTypeID()
}

func isNumber(_ value: Any) -> Bool {
    value is NSNumber && !isBoolean(value)
}

func jsonEqual(_ left: Any, _ right: Any) -> Bool {
    (try? canonicalJSON(left)) == (try? canonicalJSON(right))
}

func matchesPattern(_ value: String, _ pattern: String) -> Bool {
    guard let expression = try? NSRegularExpression(pattern: pattern) else { return false }
    let range = NSRange(value.startIndex..<value.endIndex, in: value)
    return expression.firstMatch(in: value, range: range)?.range == range
}

func validates(_ value: Any, against schema: [String: Any]) -> Bool {
    if let oneOf = schema["oneOf"] as? [[String: Any]] {
        if oneOf.filter({ validates(value, against: $0) }).count != 1 { return false }
    }
    if let anyOf = schema["anyOf"] as? [[String: Any]] {
        if !anyOf.contains(where: { validates(value, against: $0) }) { return false }
    }
    if let allOf = schema["allOf"] as? [[String: Any]] {
        if !allOf.allSatisfy({ validates(value, against: $0) }) { return false }
    }
    if let constant = schema["const"], !jsonEqual(value, constant) { return false }
    if let values = schema["enum"] as? [Any], !values.contains(where: { jsonEqual(value, $0) }) { return false }

    if let type = schema["type"] as? String {
        switch type {
        case "null": if !(value is NSNull) { return false }
        case "boolean": if !isBoolean(value) { return false }
        case "number": if !isNumber(value) { return false }
        case "integer":
            guard isNumber(value), let number = value as? NSNumber,
                  number.doubleValue.rounded() == number.doubleValue else { return false }
        case "string": if !(value is String) { return false }
        case "array": if !(value is [Any]) { return false }
        case "object": if !(value is [String: Any]) { return false }
        default: return false
        }
    }

    if let string = value as? String {
        if let minimum = schema["minLength"] as? NSNumber, string.count < minimum.intValue { return false }
        if let maximum = schema["maxLength"] as? NSNumber, string.count > maximum.intValue { return false }
        if let pattern = schema["pattern"] as? String, !matchesPattern(string, pattern) { return false }
        if schema["format"] as? String == "hive-uint64-decimal" && UInt64(string) == nil { return false }
    }
    if isNumber(value), let number = value as? NSNumber {
        if let minimum = schema["minimum"] as? NSNumber, number.doubleValue < minimum.doubleValue { return false }
        if let maximum = schema["maximum"] as? NSNumber, number.doubleValue > maximum.doubleValue { return false }
        if let minimum = schema["exclusiveMinimum"] as? NSNumber, number.doubleValue <= minimum.doubleValue { return false }
        if let maximum = schema["exclusiveMaximum"] as? NSNumber, number.doubleValue >= maximum.doubleValue { return false }
    }
    if let array = value as? [Any] {
        if let minimum = schema["minItems"] as? NSNumber, array.count < minimum.intValue { return false }
        if let maximum = schema["maxItems"] as? NSNumber, array.count > maximum.intValue { return false }
        if let itemSchema = schema["items"] as? [String: Any],
           !array.allSatisfy({ validates($0, against: itemSchema) }) { return false }
        if let prefix = schema["prefixItems"] as? [[String: Any]] {
            if array.count < prefix.count { return false }
            for (index, itemSchema) in prefix.enumerated() {
                if !validates(array[index], against: itemSchema) { return false }
            }
        }
    }
    if let object = value as? [String: Any] {
        let properties = schema["properties"] as? [String: [String: Any]] ?? [:]
        let required = Set(schema["required"] as? [String] ?? [])
        if !required.allSatisfy({ object[$0] != nil }) { return false }
        for (key, propertySchema) in properties {
            if let item = object[key], !validates(item, against: propertySchema) { return false }
        }
        let extras = object.keys.filter { properties[$0] == nil }
        if let additional = schema["additionalProperties"] as? Bool, !additional && !extras.isEmpty {
            return false
        }
        if let additional = schema["additionalProperties"] as? [String: Any] {
            for key in extras where !validates(object[key]!, against: additional) { return false }
        }
        if let maximum = schema["x-hive-max-active-cells"] as? NSNumber,
           let columns = (object["columns"] as? NSNumber)?.intValue,
           let rows = (object["rows"] as? NSNumber)?.intValue,
           columns * rows > maximum.intValue { return false }
        if schema["x-hive-ordered-minor-range"] as? Bool == true,
           let minimum = (object["minMinor"] as? NSNumber)?.intValue,
           let maximum = (object["maxMinor"] as? NSNumber)?.intValue,
           minimum > maximum { return false }
        if let names = schema["x-hive-exactly-one-of"] as? [String] {
            let present = names.filter { name in
                guard let item = object[name] else { return false }
                return !(item is NSNull)
            }
            if present.count != 1 { return false }
        }
        if let field = schema["x-hive-positive-open-terminal-revision"] as? String,
           let visibility = object[field] as? [String: Any],
           let revision = visibility["openTerminalRevision"] as? String,
           (UInt64(revision) ?? 0) == 0 { return false }
    }
    return true
}

func decodeHex(_ value: String) throws -> [UInt8] {
    if value.count % 2 != 0 { throw ContractFailure.message("MALFORMED_FRAME") }
    var bytes: [UInt8] = []
    var index = value.startIndex
    while index < value.endIndex {
        let end = value.index(index, offsetBy: 2)
        guard let byte = UInt8(value[index..<end], radix: 16) else {
            throw ContractFailure.message("MALFORMED_FRAME")
        }
        bytes.append(byte)
        index = end
    }
    return bytes
}

func encodeHex(_ bytes: [UInt8]) -> String {
    bytes.map { String(format: "%02x", $0) }.joined()
}

func readU16(_ bytes: [UInt8], _ offset: Int) -> UInt16 {
    (UInt16(bytes[offset]) << 8) | UInt16(bytes[offset + 1])
}

func readU32(_ bytes: [UInt8], _ offset: Int) -> UInt32 {
    (UInt32(bytes[offset]) << 24) | (UInt32(bytes[offset + 1]) << 16) |
    (UInt32(bytes[offset + 2]) << 8) | UInt32(bytes[offset + 3])
}

func readU64(_ bytes: [UInt8], _ offset: Int) -> UInt64 {
    var value: UInt64 = 0
    for byte in bytes[offset..<(offset + 8)] { value = (value << 8) | UInt64(byte) }
    return value
}

func writeU16(_ value: UInt16, into bytes: inout [UInt8], at offset: Int) {
    bytes[offset] = UInt8((value >> 8) & 0xff)
    bytes[offset + 1] = UInt8(value & 0xff)
}

func writeU32(_ value: UInt32, into bytes: inout [UInt8], at offset: Int) {
    for index in 0..<4 { bytes[offset + index] = UInt8((value >> UInt32((3 - index) * 8)) & 0xff) }
}

func writeU64(_ value: UInt64, into bytes: inout [UInt8], at offset: Int) {
    for index in 0..<8 { bytes[offset + index] = UInt8((value >> UInt64((7 - index) * 8)) & 0xff) }
}

func encodeHeader(_ fields: [String: Any]) throws -> [UInt8] {
    guard let typeName = fields["type"] as? String,
          let type = SessionProtocolGenerated.frameTypes[typeName],
          let flags = (fields["flags"] as? NSNumber)?.uint16Value,
          let length = (fields["payloadLength"] as? NSNumber)?.uint32Value,
          let requestText = fields["requestId"] as? String,
          let request = UInt64(requestText),
          let streamText = fields["streamSeq"] as? String,
          let stream = UInt64(streamText) else {
        throw ContractFailure.message("MALFORMED_FRAME")
    }
    var bytes = [UInt8](repeating: 0, count: SessionProtocolGenerated.headerBytes)
    for (index, byte) in SessionProtocolGenerated.magic.enumerated() { bytes[index] = byte }
    bytes[4] = SessionProtocolGenerated.protocolMajor
    bytes[5] = SessionProtocolGenerated.protocolMinor
    writeU16(type, into: &bytes, at: 6)
    writeU16(flags, into: &bytes, at: 8)
    writeU32(length, into: &bytes, at: 12)
    writeU64(request, into: &bytes, at: 16)
    writeU64(stream, into: &bytes, at: 24)
    return bytes
}

func parseHeader(_ bytes: [UInt8]) throws -> [String: Any]? {
    guard bytes.count == SessionProtocolGenerated.headerBytes,
          Array(bytes[0..<4]) == SessionProtocolGenerated.magic else {
        throw ContractFailure.message("MALFORMED_FRAME")
    }
    if bytes[4] != SessionProtocolGenerated.protocolMajor {
        throw ContractFailure.message("PROTOCOL_MISMATCH")
    }
    if bytes[5] < SessionProtocolGenerated.protocolMinMinor ||
       bytes[5] > SessionProtocolGenerated.protocolMaxMinor {
        throw ContractFailure.message("PROTOCOL_MISMATCH")
    }
    let code = readU16(bytes, 6)
    let flags = readU16(bytes, 8)
    if flags & ~SessionProtocolGenerated.allowedFlags != 0 || readU16(bytes, 10) != 0 {
        throw ContractFailure.message("MALFORMED_FRAME")
    }
    let length = readU32(bytes, 12)
    guard let type = SessionProtocolGenerated.frameTypes.first(where: { $0.value == code })?.key else {
        if code & SessionProtocolGenerated.optionalTypeBit != 0 {
            if length > SessionProtocolGenerated.controlFrameBytes {
                throw ContractFailure.message("FRAME_TOO_LARGE")
            }
            return nil
        }
        throw ContractFailure.message("UNSUPPORTED_FRAME")
    }
    let cap = SessionProtocolGenerated.rawFrameTypes.contains(type)
        ? SessionProtocolGenerated.streamFrameBytes : SessionProtocolGenerated.controlFrameBytes
    if length > cap { throw ContractFailure.message("FRAME_TOO_LARGE") }
    return [
        "type": type,
        "flags": Int(flags),
        "payloadLength": Int(length),
        "requestId": String(readU64(bytes, 16)),
        "streamSeq": String(readU64(bytes, 24)),
    ]
}

func reduceEvent(_ state: [String: Any], _ event: [String: Any]) throws -> [String: Any] {
    if state["paused"] as? Bool == true || !(state["corruption"] is NSNull) { return state }
    guard let eventId = event["eventId"] as? String,
          let sequenceText = event["seq"] as? String,
          let sequence = UInt64(sequenceText),
          let entity = event["entity"] as? [String: Any],
          let kind = entity["kind"] as? String,
          let id = entity["id"] as? String,
          let revisionText = event["entityRevision"] as? String,
          let revision = UInt64(revisionText) else {
        throw ContractFailure.message("invalid reducer event")
    }
    let encoded = try canonicalJSON(event)
    var seen = state["seen"] as? [String: String] ?? [:]
    if let prior = seen[eventId] {
        if prior == encoded { return state }
        var corrupted = state
        corrupted["corruption"] = "conflicting duplicate \(eventId)"
        return corrupted
    }
    let highWater = UInt64(state["highWaterSeq"] as? String ?? "0")!
    if sequence != highWater + 1 {
        var paused = state
        paused["paused"] = true
        paused["recovery"] = "SNAPSHOT_REQUIRED"
        return paused
    }
    seen[eventId] = encoded
    var entities = state["entities"] as? [String: Any] ?? [:]
    let generation = (entity["generation"] as? NSNumber)?.stringValue ?? "-"
    let entityKey = kind == "agent"
        ? "agent:\(id)"
        : "\(kind):\(id):\(generation)"
    let existingRevision = ((entities[entityKey] as? [String: Any])?["entityRevision"] as? String).flatMap(UInt64.init)
    if existingRevision == nil || revision >= existingRevision! {
        entities[entityKey] = [
            "entityRevision": revisionText,
            "eventId": eventId,
            "kind": event["kind"]!,
            "occurredAt": event["occurredAt"]!,
            "source": event["source"]!,
            "data": event["data"]!,
        ]
    }
    var result = state
    result["highWaterSeq"] = sequenceText
    result["entities"] = entities
    result["seen"] = seen
    return result
}

guard CommandLine.arguments.count == 4 else {
    fatalError("usage: swift SessionProtocol.generated.swift schema.json corpus.json reducer.json")
}

let schemaDocument = try readJSON(CommandLine.arguments[1]) as! [String: Any]
let schemas = schemaDocument["schemas"] as! [String: [String: Any]]
let corpus = try readJSON(CommandLine.arguments[2]) as! [String: Any]
let reducerCorpus = try readJSON(CommandLine.arguments[3]) as! [String: Any]
var validEncodings: [String: String] = [:]
var canonicalDigests: [String: String] = [:]
var invalidRejected: [String] = []

for item in corpus["valid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let schemaName = item["schema"] as! String
    let value = item["value"]!
    guard validates(value, against: schemas[schemaName]!) else {
        throw ContractFailure.message("Swift rejected valid case: \(name)")
    }
    let canonical = try canonicalJSON(value)
    validEncodings[name] = canonical
    canonicalDigests[name] = SHA256.hash(data: Data(canonical.utf8))
        .map { String(format: "%02x", $0) }.joined()
}
for item in corpus["invalid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let schemaName = item["schema"] as! String
    if validates(item["value"]!, against: schemas[schemaName]!) {
        throw ContractFailure.message("Swift accepted invalid case: \(name)")
    }
    invalidRejected.append(name)
}

let headers = corpus["frameHeaders"] as! [String: Any]
var validHeaders: [String] = []
for item in headers["valid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let fields = item["fields"] as! [String: Any]
    let encoded = try encodeHeader(fields)
    guard encodeHex(encoded) == item["hex"] as! String,
          try canonicalJSON(parseHeader(encoded)!) == canonicalJSON(fields) else {
        throw ContractFailure.message("Swift frame mismatch: \(name)")
    }
    validHeaders.append(name)
}
var ignoredHeaders: [String] = []
for item in headers["ignored"] as! [[String: Any]] {
    let name = item["name"] as! String
    guard try parseHeader(decodeHex(item["hex"] as! String)) == nil else {
        throw ContractFailure.message("Swift did not ignore optional frame: \(name)")
    }
    ignoredHeaders.append(name)
}
var invalidHeaders: [String: String] = [:]
for item in headers["invalid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let expected = item["error"] as! String
    do {
        _ = try parseHeader(decodeHex(item["hex"] as! String))
        throw ContractFailure.message("Swift accepted invalid frame: \(name)")
    } catch let error as ContractFailure {
        guard error.description == expected else { throw error }
        invalidHeaders[name] = expected
    }
}

var reducerPrefixes: [String: [String]] = [:]
for scenario in reducerCorpus["scenarios"] as! [[String: Any]] {
    let name = scenario["name"] as! String
    let events = scenario["events"] as! [[String: Any]]
    let expected = scenario["prefixes"] as! [[String: Any]]
    var state: [String: Any] = [
        "highWaterSeq": "0", "paused": false, "recovery": NSNull(), "corruption": NSNull(),
        "entities": [String: Any](), "seen": [String: String](),
    ]
    var prefixes: [String] = []
    for (index, event) in events.enumerated() {
        state = try reduceEvent(state, event)
        let encoded = try canonicalJSON(state)
        guard encoded == (try canonicalJSON(expected[index])) else {
            throw ContractFailure.message("Swift reducer mismatch: \(name) prefix \(index + 1)")
        }
        prefixes.append(encoded)
    }
    reducerPrefixes[name] = prefixes
}

let report: [String: Any] = [
    "validEncodings": validEncodings,
    "canonicalDigests": canonicalDigests,
    "invalidRejected": invalidRejected,
    "validHeaders": validHeaders,
    "ignoredHeaders": ignoredHeaders,
    "invalidHeaders": invalidHeaders,
    "reducerPrefixes": reducerPrefixes,
]
print(try canonicalJSON(report))
