#!/usr/bin/env bun
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { z } from "zod";
import {
  CHECKPOINT_HEADER,
  FRAME_FLAGS,
  FRAME_HEADER,
  FRAME_TYPES,
  GHOSTTY_BRIDGE_EVENTS,
  INPUT_ARBITER_STATES,
  INPUT_EVIDENCE_LEVELS,
  RAW_BYTE_FRAME_TYPES,
  SESSION_PROTOCOL_CONTRACT,
  SESSION_PROTOCOL_MINOR_RANGE,
  SESSION_PROTOCOL_VERSION,
  SESSION_WIRE_SCHEMAS,
  TERMINAL_LIMITS,
  WIRE_ERROR_CODES,
} from "../../src/schemas/session-protocol";
import {
  STATUS_CONTRACT,
  STATUS_WIRE_SCHEMAS,
} from "../../src/schemas/status-envelope";
import { HV1_CAPABILITY_WIRE_SCHEMAS } from "../../src/schemas/capability";
import {
  MESSAGE_TERMINAL_CONTRACT,
  MESSAGE_TERMINAL_WIRE_SCHEMAS,
} from "../../src/schemas/message-envelope";
import { buildReducerCorpus, buildWireCorpus } from "./fixtures";

export const FIXTURE_DIRECTORY = resolve(
  import.meta.dir,
  "../../workspace/Tests/WorkspaceCoreTests/Fixtures",
);

export const GENERATED_FILES = {
  schema: resolve(FIXTURE_DIRECTORY, "session-protocol.schema.json"),
  corpus: resolve(FIXTURE_DIRECTORY, "session-protocol-corpus.json"),
  reducer: resolve(FIXTURE_DIRECTORY, "reducer-parity-corpus.json"),
  swift: resolve(FIXTURE_DIRECTORY, "SessionProtocol.generated.swift"),
  zig: resolve(FIXTURE_DIRECTORY, "session_protocol.generated.zig"),
} as const;

export const WIRE_SCHEMA_CATALOG = {
  ...SESSION_WIRE_SCHEMAS,
  ...STATUS_WIRE_SCHEMAS,
  ...HV1_CAPABILITY_WIRE_SCHEMAS,
  ...MESSAGE_TERMINAL_WIRE_SCHEMAS,
} as const;

const prettyJson = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

function renderSchemaDocument(): string {
  const schemas = Object.fromEntries(
    Object.entries(WIRE_SCHEMA_CATALOG).map(([name, schema]) => [
      name,
      z.toJSONSchema(schema),
    ]),
  );
  return prettyJson({
    schemaVersion: 1,
    generatedFrom: [
      "src/schemas/session-protocol.ts",
      "src/schemas/status-envelope.ts",
      "src/schemas/capability.ts",
      "src/schemas/message-envelope.ts",
    ],
    schemas,
    contract: {
      session: SESSION_PROTOCOL_CONTRACT,
      status: STATUS_CONTRACT,
      messageTerminalBinding: MESSAGE_TERMINAL_CONTRACT,
    },
  });
}

const swiftDictionary = (value: Record<string, number>): string =>
  Object.entries(value)
    .map(([name, number]) => `        "${name}": 0x${number.toString(16).padStart(4, "0")}`)
    .join(",\n");

function renderSwift(): string {
  return `// Generated by test/session-host-conformance/generate.ts. Do not edit.
import CoreFoundation
import Foundation

enum SessionProtocolGenerated {
    static let protocolMajor: UInt8 = ${SESSION_PROTOCOL_VERSION.major}
    static let protocolMinor: UInt8 = ${SESSION_PROTOCOL_VERSION.minor}
    static let protocolMinMinor: UInt8 = ${SESSION_PROTOCOL_MINOR_RANGE.min}
    static let protocolMaxMinor: UInt8 = ${SESSION_PROTOCOL_MINOR_RANGE.max}
    static let headerBytes = ${FRAME_HEADER.bytes}
    static let optionalTypeBit: UInt16 = 0x${FRAME_HEADER.optionalTypeBit.toString(16)}
    static let magic: [UInt8] = [${FRAME_HEADER.magicBytes.join(", ")}]
    static let allowedFlags: UInt16 = ${FRAME_FLAGS.allowedMask}
    static let controlFrameBytes = ${TERMINAL_LIMITS.controlJsonBytesPerFrame}
    static let streamFrameBytes = ${TERMINAL_LIMITS.streamChunkBytes}
    static let frameTypes: [String: UInt16] = [
${swiftDictionary(FRAME_TYPES)}
    ]
    static let rawFrameTypes: Set<String> = [${RAW_BYTE_FRAME_TYPES.map((name) => `"${name}"`).join(", ")}]
}

enum ContractFailure: Error, CustomStringConvertible {
    case message(String)
    var description: String {
        switch self { case .message(let value): return value }
    }
}

func readJSON(_ path: String) throws -> Any {
    try JSONSerialization.jsonObject(with: Data(contentsOf: URL(fileURLWithPath: path)))
}

func canonicalJSON(_ value: Any) throws -> String {
    let data = try JSONSerialization.data(withJSONObject: value, options: [.sortedKeys, .withoutEscapingSlashes, .fragmentsAllowed])
    guard let result = String(data: data, encoding: .utf8) else {
        throw ContractFailure.message("invalid UTF-8 after JSON encoding")
    }
    return result
}

func isBoolean(_ value: Any) -> Bool {
    guard let number = value as? NSNumber else { return false }
    return CFGetTypeID(number) == CFBooleanGetTypeID()
}

func isNumber(_ value: Any) -> Bool {
    value is NSNumber && !isBoolean(value)
}

func jsonEqual(_ left: Any, _ right: Any) -> Bool {
    (try? canonicalJSON(left)) == (try? canonicalJSON(right))
}

func matchesPattern(_ value: String, _ pattern: String) -> Bool {
    guard let expression = try? NSRegularExpression(pattern: pattern) else { return false }
    let range = NSRange(value.startIndex..<value.endIndex, in: value)
    return expression.firstMatch(in: value, range: range)?.range == range
}

func validates(_ value: Any, against schema: [String: Any]) -> Bool {
    if let oneOf = schema["oneOf"] as? [[String: Any]] {
        if oneOf.filter({ validates(value, against: $0) }).count != 1 { return false }
    }
    if let anyOf = schema["anyOf"] as? [[String: Any]] {
        if !anyOf.contains(where: { validates(value, against: $0) }) { return false }
    }
    if let allOf = schema["allOf"] as? [[String: Any]] {
        if !allOf.allSatisfy({ validates(value, against: $0) }) { return false }
    }
    if let constant = schema["const"], !jsonEqual(value, constant) { return false }
    if let values = schema["enum"] as? [Any], !values.contains(where: { jsonEqual(value, $0) }) { return false }

    if let type = schema["type"] as? String {
        switch type {
        case "null": if !(value is NSNull) { return false }
        case "boolean": if !isBoolean(value) { return false }
        case "number": if !isNumber(value) { return false }
        case "integer":
            guard isNumber(value), let number = value as? NSNumber,
                  number.doubleValue.rounded() == number.doubleValue else { return false }
        case "string": if !(value is String) { return false }
        case "array": if !(value is [Any]) { return false }
        case "object": if !(value is [String: Any]) { return false }
        default: return false
        }
    }

    if let string = value as? String {
        if let minimum = schema["minLength"] as? NSNumber, string.count < minimum.intValue { return false }
        if let maximum = schema["maxLength"] as? NSNumber, string.count > maximum.intValue { return false }
        if let pattern = schema["pattern"] as? String, !matchesPattern(string, pattern) { return false }
        if schema["format"] as? String == "hive-uint64-decimal" && UInt64(string) == nil { return false }
    }
    if isNumber(value), let number = value as? NSNumber {
        if let minimum = schema["minimum"] as? NSNumber, number.doubleValue < minimum.doubleValue { return false }
        if let maximum = schema["maximum"] as? NSNumber, number.doubleValue > maximum.doubleValue { return false }
        if let minimum = schema["exclusiveMinimum"] as? NSNumber, number.doubleValue <= minimum.doubleValue { return false }
        if let maximum = schema["exclusiveMaximum"] as? NSNumber, number.doubleValue >= maximum.doubleValue { return false }
    }
    if let array = value as? [Any] {
        if let minimum = schema["minItems"] as? NSNumber, array.count < minimum.intValue { return false }
        if let maximum = schema["maxItems"] as? NSNumber, array.count > maximum.intValue { return false }
        if let itemSchema = schema["items"] as? [String: Any],
           !array.allSatisfy({ validates($0, against: itemSchema) }) { return false }
        if let prefix = schema["prefixItems"] as? [[String: Any]] {
            if array.count < prefix.count { return false }
            for (index, itemSchema) in prefix.enumerated() {
                if !validates(array[index], against: itemSchema) { return false }
            }
        }
    }
    if let object = value as? [String: Any] {
        let properties = schema["properties"] as? [String: [String: Any]] ?? [:]
        let required = Set(schema["required"] as? [String] ?? [])
        if !required.allSatisfy({ object[$0] != nil }) { return false }
        for (key, propertySchema) in properties {
            if let item = object[key], !validates(item, against: propertySchema) { return false }
        }
        let extras = object.keys.filter { properties[$0] == nil }
        if let additional = schema["additionalProperties"] as? Bool, !additional && !extras.isEmpty {
            return false
        }
        if let additional = schema["additionalProperties"] as? [String: Any] {
            for key in extras where !validates(object[key]!, against: additional) { return false }
        }
        if let maximum = schema["x-hive-max-active-cells"] as? NSNumber,
           let columns = (object["columns"] as? NSNumber)?.intValue,
           let rows = (object["rows"] as? NSNumber)?.intValue,
           columns * rows > maximum.intValue { return false }
        if schema["x-hive-ordered-minor-range"] as? Bool == true,
           let minimum = (object["minMinor"] as? NSNumber)?.intValue,
           let maximum = (object["maxMinor"] as? NSNumber)?.intValue,
           minimum > maximum { return false }
        if let names = schema["x-hive-exactly-one-of"] as? [String] {
            let present = names.filter { name in
                guard let item = object[name] else { return false }
                return !(item is NSNull)
            }
            if present.count != 1 { return false }
        }
        if let field = schema["x-hive-positive-open-terminal-revision"] as? String,
           let visibility = object[field] as? [String: Any],
           let revision = visibility["openTerminalRevision"] as? String,
           (UInt64(revision) ?? 0) == 0 { return false }
    }
    return true
}

func decodeHex(_ value: String) throws -> [UInt8] {
    if value.count % 2 != 0 { throw ContractFailure.message("MALFORMED_FRAME") }
    var bytes: [UInt8] = []
    var index = value.startIndex
    while index < value.endIndex {
        let end = value.index(index, offsetBy: 2)
        guard let byte = UInt8(value[index..<end], radix: 16) else {
            throw ContractFailure.message("MALFORMED_FRAME")
        }
        bytes.append(byte)
        index = end
    }
    return bytes
}

func encodeHex(_ bytes: [UInt8]) -> String {
    bytes.map { String(format: "%02x", $0) }.joined()
}

func readU16(_ bytes: [UInt8], _ offset: Int) -> UInt16 {
    (UInt16(bytes[offset]) << 8) | UInt16(bytes[offset + 1])
}

func readU32(_ bytes: [UInt8], _ offset: Int) -> UInt32 {
    (UInt32(bytes[offset]) << 24) | (UInt32(bytes[offset + 1]) << 16) |
    (UInt32(bytes[offset + 2]) << 8) | UInt32(bytes[offset + 3])
}

func readU64(_ bytes: [UInt8], _ offset: Int) -> UInt64 {
    var value: UInt64 = 0
    for byte in bytes[offset..<(offset + 8)] { value = (value << 8) | UInt64(byte) }
    return value
}

func writeU16(_ value: UInt16, into bytes: inout [UInt8], at offset: Int) {
    bytes[offset] = UInt8((value >> 8) & 0xff)
    bytes[offset + 1] = UInt8(value & 0xff)
}

func writeU32(_ value: UInt32, into bytes: inout [UInt8], at offset: Int) {
    for index in 0..<4 { bytes[offset + index] = UInt8((value >> UInt32((3 - index) * 8)) & 0xff) }
}

func writeU64(_ value: UInt64, into bytes: inout [UInt8], at offset: Int) {
    for index in 0..<8 { bytes[offset + index] = UInt8((value >> UInt64((7 - index) * 8)) & 0xff) }
}

func encodeHeader(_ fields: [String: Any]) throws -> [UInt8] {
    guard let typeName = fields["type"] as? String,
          let type = SessionProtocolGenerated.frameTypes[typeName],
          let flags = (fields["flags"] as? NSNumber)?.uint16Value,
          let length = (fields["payloadLength"] as? NSNumber)?.uint32Value,
          let requestText = fields["requestId"] as? String,
          let request = UInt64(requestText),
          let streamText = fields["streamSeq"] as? String,
          let stream = UInt64(streamText) else {
        throw ContractFailure.message("MALFORMED_FRAME")
    }
    var bytes = [UInt8](repeating: 0, count: SessionProtocolGenerated.headerBytes)
    for (index, byte) in SessionProtocolGenerated.magic.enumerated() { bytes[index] = byte }
    bytes[4] = SessionProtocolGenerated.protocolMajor
    bytes[5] = SessionProtocolGenerated.protocolMinor
    writeU16(type, into: &bytes, at: 6)
    writeU16(flags, into: &bytes, at: 8)
    writeU32(length, into: &bytes, at: 12)
    writeU64(request, into: &bytes, at: 16)
    writeU64(stream, into: &bytes, at: 24)
    return bytes
}

func parseHeader(_ bytes: [UInt8]) throws -> [String: Any]? {
    guard bytes.count == SessionProtocolGenerated.headerBytes,
          Array(bytes[0..<4]) == SessionProtocolGenerated.magic else {
        throw ContractFailure.message("MALFORMED_FRAME")
    }
    if bytes[4] != SessionProtocolGenerated.protocolMajor {
        throw ContractFailure.message("PROTOCOL_MISMATCH")
    }
    if bytes[5] < SessionProtocolGenerated.protocolMinMinor ||
       bytes[5] > SessionProtocolGenerated.protocolMaxMinor {
        throw ContractFailure.message("PROTOCOL_MISMATCH")
    }
    let code = readU16(bytes, 6)
    let flags = readU16(bytes, 8)
    if flags & ~SessionProtocolGenerated.allowedFlags != 0 || readU16(bytes, 10) != 0 {
        throw ContractFailure.message("MALFORMED_FRAME")
    }
    let length = readU32(bytes, 12)
    guard let type = SessionProtocolGenerated.frameTypes.first(where: { $0.value == code })?.key else {
        if code & SessionProtocolGenerated.optionalTypeBit != 0 {
            if length > SessionProtocolGenerated.controlFrameBytes {
                throw ContractFailure.message("FRAME_TOO_LARGE")
            }
            return nil
        }
        throw ContractFailure.message("UNSUPPORTED_FRAME")
    }
    let cap = SessionProtocolGenerated.rawFrameTypes.contains(type)
        ? SessionProtocolGenerated.streamFrameBytes : SessionProtocolGenerated.controlFrameBytes
    if length > cap { throw ContractFailure.message("FRAME_TOO_LARGE") }
    return [
        "type": type,
        "flags": Int(flags),
        "payloadLength": Int(length),
        "requestId": String(readU64(bytes, 16)),
        "streamSeq": String(readU64(bytes, 24)),
    ]
}

func reduceEvent(_ state: [String: Any], _ event: [String: Any]) throws -> [String: Any] {
    if state["paused"] as? Bool == true || !(state["corruption"] is NSNull) { return state }
    guard let eventId = event["eventId"] as? String,
          let sequenceText = event["seq"] as? String,
          let sequence = UInt64(sequenceText),
          let entity = event["entity"] as? [String: Any],
          let kind = entity["kind"] as? String,
          let id = entity["id"] as? String,
          let revisionText = event["entityRevision"] as? String,
          let revision = UInt64(revisionText) else {
        throw ContractFailure.message("invalid reducer event")
    }
    let encoded = try canonicalJSON(event)
    var seen = state["seen"] as? [String: String] ?? [:]
    if let prior = seen[eventId] {
        if prior == encoded { return state }
        var corrupted = state
        corrupted["corruption"] = "conflicting duplicate \\(eventId)"
        return corrupted
    }
    let highWater = UInt64(state["highWaterSeq"] as? String ?? "0")!
    if sequence != highWater + 1 {
        var paused = state
        paused["paused"] = true
        paused["recovery"] = "SNAPSHOT_REQUIRED"
        return paused
    }
    seen[eventId] = encoded
    var entities = state["entities"] as? [String: Any] ?? [:]
    let generation = (entity["generation"] as? NSNumber)?.stringValue ?? "-"
    let entityKey = "\\(kind):\\(id):\\(generation)"
    let existingRevision = ((entities[entityKey] as? [String: Any])?["entityRevision"] as? String).flatMap(UInt64.init)
    if existingRevision == nil || revision >= existingRevision! {
        entities[entityKey] = [
            "entityRevision": revisionText,
            "eventId": eventId,
            "kind": event["kind"]!,
            "occurredAt": event["occurredAt"]!,
            "source": event["source"]!,
            "data": event["data"]!,
        ]
    }
    var result = state
    result["highWaterSeq"] = sequenceText
    result["entities"] = entities
    result["seen"] = seen
    return result
}

guard CommandLine.arguments.count == 4 else {
    fatalError("usage: swift SessionProtocol.generated.swift schema.json corpus.json reducer.json")
}

let schemaDocument = try readJSON(CommandLine.arguments[1]) as! [String: Any]
let schemas = schemaDocument["schemas"] as! [String: [String: Any]]
let corpus = try readJSON(CommandLine.arguments[2]) as! [String: Any]
let reducerCorpus = try readJSON(CommandLine.arguments[3]) as! [String: Any]
var validEncodings: [String: String] = [:]
var invalidRejected: [String] = []

for item in corpus["valid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let schemaName = item["schema"] as! String
    let value = item["value"]!
    guard validates(value, against: schemas[schemaName]!) else {
        throw ContractFailure.message("Swift rejected valid case: \\(name)")
    }
    validEncodings[name] = try canonicalJSON(value)
}
for item in corpus["invalid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let schemaName = item["schema"] as! String
    if validates(item["value"]!, against: schemas[schemaName]!) {
        throw ContractFailure.message("Swift accepted invalid case: \\(name)")
    }
    invalidRejected.append(name)
}

let headers = corpus["frameHeaders"] as! [String: Any]
var validHeaders: [String] = []
for item in headers["valid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let fields = item["fields"] as! [String: Any]
    let encoded = try encodeHeader(fields)
    guard encodeHex(encoded) == item["hex"] as! String,
          try canonicalJSON(parseHeader(encoded)!) == canonicalJSON(fields) else {
        throw ContractFailure.message("Swift frame mismatch: \\(name)")
    }
    validHeaders.append(name)
}
var ignoredHeaders: [String] = []
for item in headers["ignored"] as! [[String: Any]] {
    let name = item["name"] as! String
    guard try parseHeader(decodeHex(item["hex"] as! String)) == nil else {
        throw ContractFailure.message("Swift did not ignore optional frame: \\(name)")
    }
    ignoredHeaders.append(name)
}
var invalidHeaders: [String: String] = [:]
for item in headers["invalid"] as! [[String: Any]] {
    let name = item["name"] as! String
    let expected = item["error"] as! String
    do {
        _ = try parseHeader(decodeHex(item["hex"] as! String))
        throw ContractFailure.message("Swift accepted invalid frame: \\(name)")
    } catch let error as ContractFailure {
        guard error.description == expected else { throw error }
        invalidHeaders[name] = expected
    }
}

var reducerPrefixes: [String: [String]] = [:]
for scenario in reducerCorpus["scenarios"] as! [[String: Any]] {
    let name = scenario["name"] as! String
    let events = scenario["events"] as! [[String: Any]]
    let expected = scenario["prefixes"] as! [[String: Any]]
    var state: [String: Any] = [
        "highWaterSeq": "0", "paused": false, "recovery": NSNull(), "corruption": NSNull(),
        "entities": [String: Any](), "seen": [String: String](),
    ]
    var prefixes: [String] = []
    for (index, event) in events.enumerated() {
        state = try reduceEvent(state, event)
        let encoded = try canonicalJSON(state)
        guard encoded == (try canonicalJSON(expected[index])) else {
            throw ContractFailure.message("Swift reducer mismatch: \\(name) prefix \\(index + 1)")
        }
        prefixes.append(encoded)
    }
    reducerPrefixes[name] = prefixes
}

let report: [String: Any] = [
    "validEncodings": validEncodings,
    "invalidRejected": invalidRejected,
    "validHeaders": validHeaders,
    "ignoredHeaders": ignoredHeaders,
    "invalidHeaders": invalidHeaders,
    "reducerPrefixes": reducerPrefixes,
]
print(try canonicalJSON(report))
`;
}

const zigName = (value: string): string => value
  .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
  .toLowerCase()
  .replaceAll("-", "_");
const zigIdentifier = (value: string): string => {
  const name = zigName(value);
  return name === "error" ? `@"${name}"` : name;
};

function renderZig(): string {
  const frameTypes = Object.entries(FRAME_TYPES)
    .map(([name, value]) => `    pub const ${zigIdentifier(name)}: u16 = 0x${value.toString(16).padStart(4, "0")};`)
    .join("\n");
  const errors = WIRE_ERROR_CODES.map((name) => `    ${zigName(name)},`).join("\n");
  const states = INPUT_ARBITER_STATES.map((name) => `    ${zigName(name)},`).join("\n");
  const evidence = INPUT_EVIDENCE_LEVELS.map((name) => `    ${zigName(name)},`).join("\n");
  const bridgeEvents = Object.entries(GHOSTTY_BRIDGE_EVENTS)
    .map(([name, value]) => `    ${zigName(name)} = ${value},`)
    .join("\n");
  const wireSchemas = Object.keys(SESSION_WIRE_SCHEMAS)
    .map((name) => `    pub const ${zigName(name)} = "${name}";`)
    .join("\n");
  return `// Generated by test/session-host-conformance/generate.ts. Do not edit.
// Zig 0.15.2 compilation is provisioned by WP1; WP0 intentionally does not install it.

pub const protocol_major: u8 = ${SESSION_PROTOCOL_VERSION.major};
pub const protocol_minor: u8 = ${SESSION_PROTOCOL_VERSION.minor};
pub const protocol_min_minor: u8 = ${SESSION_PROTOCOL_MINOR_RANGE.min};
pub const protocol_max_minor: u8 = ${SESSION_PROTOCOL_MINOR_RANGE.max};
pub const frame_header_bytes: usize = ${FRAME_HEADER.bytes};
pub const frame_magic = "${FRAME_HEADER.magic}";
pub const frame_optional_type_bit: u16 = 0x${FRAME_HEADER.optionalTypeBit.toString(16).padStart(4, "0")};
pub const frame_allowed_flags: u16 = 0x${FRAME_FLAGS.allowedMask.toString(16).padStart(4, "0")};

pub const frame_flag = struct {
    pub const response: u16 = 0x${FRAME_FLAGS.response.toString(16).padStart(4, "0")};
    pub const final: u16 = 0x${FRAME_FLAGS.final.toString(16).padStart(4, "0")};
    pub const error_flag: u16 = 0x${FRAME_FLAGS.error.toString(16).padStart(4, "0")};
    pub const content_sensitive: u16 = 0x${FRAME_FLAGS.contentSensitive.toString(16).padStart(4, "0")};
};

pub const frame_type = struct {
${frameTypes}
};

pub const wire_schema = struct {
${wireSchemas}
};

pub const wire_error = enum {
${errors}
};

pub const input_state = enum {
${states}
};

pub const input_evidence = enum {
${evidence}
};

pub const ghostty_bridge_event = enum(u8) {
${bridgeEvents}
};

pub const checkpoint = struct {
    pub const magic = "${CHECKPOINT_HEADER.magic}";
    pub const version: u16 = ${CHECKPOINT_HEADER.version};
    pub const header_bytes: usize = ${CHECKPOINT_HEADER.bytes};
    pub const flags: u32 = ${CHECKPOINT_HEADER.flags};
    pub const engine_build_id_bytes: usize = ${CHECKPOINT_HEADER.engineBuildIdBytes};
    pub const payload_sha256_bytes: usize = ${CHECKPOINT_HEADER.payloadSha256Bytes};
};

pub const limits = struct {
    pub const live_sessions_per_hive_home: usize = ${TERMINAL_LIMITS.liveSessionsPerHiveHome};
    pub const viewers_per_generation: usize = ${TERMINAL_LIMITS.authenticatedViewersPerGeneration};
    pub const control_json_bytes: usize = ${TERMINAL_LIMITS.controlJsonBytesPerFrame};
    pub const stream_chunk_bytes: usize = ${TERMINAL_LIMITS.streamChunkBytes};
    pub const automated_message_bytes: usize = ${TERMINAL_LIMITS.automatedMessageBytes};
    pub const viewer_queue_bytes: usize = ${TERMINAL_LIMITS.viewerUnacknowledgedOutputBytes};
    pub const checkpoint_bytes: usize = ${TERMINAL_LIMITS.checkpointBytes};
    pub const terminal_disk_bytes: u64 = ${TERMINAL_LIMITS.terminalDiskBytesPerHiveHome};
    pub const control_rpc_timeout_ms: u64 = ${TERMINAL_LIMITS.controlRpcTimeoutMilliseconds};
    pub const attach_grant_timeout_ms: u64 = ${TERMINAL_LIMITS.attachGrantTimeoutMilliseconds};
    pub const visibility_renewal_ms: u64 = ${TERMINAL_LIMITS.visibilityRenewalMilliseconds};
    pub const visibility_expiry_ms: u64 = ${TERMINAL_LIMITS.visibilityExpiryMilliseconds};
    pub const connection_ping_interval_ms: u64 = ${TERMINAL_LIMITS.connectionPingIntervalMilliseconds};
    pub const missed_pong_intervals: u8 = ${TERMINAL_LIMITS.missedPongIntervalsBeforeDetach};
};

// Payloads remain schema-driven; no hand-maintained Zig payload structs live here.
pub const schema_fixture = @embedFile("session-protocol.schema.json");
pub const wire_corpus_fixture = @embedFile("session-protocol-corpus.json");
pub const reducer_corpus_fixture = @embedFile("reducer-parity-corpus.json");
`;
}

export function renderGeneratedArtifacts(): Readonly<Record<string, string>> {
  return {
    [GENERATED_FILES.schema]: renderSchemaDocument(),
    [GENERATED_FILES.corpus]: prettyJson(buildWireCorpus()),
    [GENERATED_FILES.reducer]: prettyJson(buildReducerCorpus()),
    [GENERATED_FILES.swift]: renderSwift(),
    [GENERATED_FILES.zig]: renderZig(),
  };
}

export async function writeGeneratedArtifacts(): Promise<void> {
  await mkdir(FIXTURE_DIRECTORY, { recursive: true });
  for (const [path, contents] of Object.entries(renderGeneratedArtifacts())) {
    await writeFile(path, contents);
  }
}

if (import.meta.main) {
  await writeGeneratedArtifacts();
  for (const path of Object.values(GENERATED_FILES)) console.log(path);
}
