/**
 * Runs every identity-under-motion scenario and writes EVIDENCE.md.
 *
 *   bun run prototypes/project-identity/harness/run.ts
 *
 * Exits non-zero if any scenario fails. Skipped scenarios are reported, never hidden.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { prototypeRoot } from "./helper";
import { runScenarios } from "./scenarios";
import type { ScenarioResult } from "./scenarios";

const MARK: Record<ScenarioResult["status"], string> = { pass: "PASS", fail: "FAIL", skipped: "SKIP" };

/**
 * Temp paths, inode numbers, and freshly minted UUIDs differ on every run, and this file
 * is committed. Redaction keeps the log stable in Git while preserving the only thing the
 * evidence actually rests on: whether two values are the same or different. Volatile values
 * are numbered in first-seen order within a scenario, so `#1 != #2` still reads as a
 * mismatch and `#1 == #1` still reads as a match.
 */
const UUID = /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/gi;
const FIXTURE_ROOT = /(?:\/private)?\/(?:var\/folders|tmp)\/\S*?hive-identity-[A-Za-z0-9]+/g;
/** Inode and device numbers. Small counts (500 cycles) stay literal. */
const LARGE_NUMBER = /\b\d{7,}\b/g;

function redact(observations: string[]): string[] {
  const labels = new Map<string, string>();
  const label = (value: string): string => {
    let existing = labels.get(value);
    if (!existing) {
      existing = `#${labels.size + 1}`;
      labels.set(value, existing);
    }
    return existing;
  };
  return observations.map((line) =>
    line
      .replace(FIXTURE_ROOT, "<fixture>")
      .replace(UUID, label)
      .replace(LARGE_NUMBER, label),
  );
}

function renderEvidence(results: ScenarioResult[]): string {
  const passed = results.filter((r) => r.status === "pass").length;
  const failed = results.filter((r) => r.status === "fail").length;
  const skipped = results.filter((r) => r.status === "skipped").length;

  const lines: string[] = [
    "# Identity under motion: evidence",
    "",
    "Generated by `bun run prototypes/project-identity/harness/run.ts` on macOS/APFS.",
    "Every line under **Observed** is a fact the harness measured on the machine that ran it,",
    "not a fact quoted from documentation.",
    "",
    `${passed} passed, ${failed} failed, ${skipped} skipped.`,
    "",
  ];

  for (const result of results) {
    lines.push(`## ${MARK[result.status]} — ${result.title}`, "");
    lines.push(`\`${result.id}\``, "");
    lines.push(`**Proves.** ${result.proves}`, "");
    if (result.detail) lines.push(`**${result.status === "skipped" ? "Skipped" : "Failure"}.** ${result.detail}`, "");
    if (result.observations.length > 0) {
      lines.push("**Observed.**", "");
      for (const observation of redact(result.observations)) lines.push(`- ${observation}`);
      lines.push("");
    }
  }

  lines.push(
    "## Not tested: SMB and other network volumes",
    "",
    "No SMB server was reachable from the machine that produced this log, and standing one up",
    "would have made the result depend on an unrecorded server configuration. Nothing here",
    "should be read as evidence about network volumes. The specific claims that do not transfer:",
    "",
    "- **Inode stability.** The refusal logic rests on `dev`/`ino`/`birthtimeMs` changing when a",
    "  directory is replaced. An SMB client synthesizes inode numbers, and a server may reissue",
    "  them across remounts. If it does, `findByEvidence` can both miss a real move and, far worse,",
    "  match an unrelated directory.",
    "- **Bookmark resolution.** The path-first behavior measured below was measured on APFS. A",
    "  bookmark to an unmounted share has no file to resolve at all.",
    "- **Case and normalization behavior.** These are properties of the server's filesystem, not of",
    "  the SMB client. `describeVolume` probes rather than assumes, so it should degrade correctly,",
    "  but that has not been demonstrated.",
    "",
    "The experiment that would settle it: export one case-sensitive and one case-insensitive share",
    "from a known server, run the same scenarios against both, then unmount and remount between",
    "each step and re-check that `ino` and `birthtimeMs` survive. Until that runs, a network volume",
    "should resolve to `BLOCKED_CONFIG` rather than silently rely on evidence it cannot trust.",
    "",
  );

  return lines.join("\n");
}

const results = runScenarios();
const evidencePath = join(prototypeRoot, "EVIDENCE.md");
writeFileSync(evidencePath, renderEvidence(results));

for (const result of results) {
  const suffix = result.detail ? ` — ${result.detail}` : "";
  console.log(`${MARK[result.status].padEnd(4)} ${result.id}${suffix}`);
}

const failed = results.filter((r) => r.status === "fail");
const skipped = results.filter((r) => r.status === "skipped");
console.log(
  `\n${results.length - failed.length - skipped.length} passed, ${failed.length} failed, ${skipped.length} skipped`,
);
console.log(`evidence written to ${evidencePath}`);

if (failed.length > 0) process.exit(1);
