import { TERMINAL_LIMITS } from "./limits";

export const CHECKPOINT_HEADER = {
  bytes: 116,
  magic: "HVTCP001",
  version: 1,
  flags: 0,
  byteOrder: "network",
  cellPixelEncoding: "unsigned-fixed-16.16",
  payloadMaxBytes: TERMINAL_LIMITS.checkpointBytes,
  engineBuildIdBytes: 32,
  payloadSha256Bytes: 32,
  widths: {
    magic: 8,
    version: 2,
    headerBytes: 2,
    flags: 4,
    throughSeq: 8,
    createdMonoNanos: 8,
    columns: 4,
    rows: 4,
    cellWidthPx: 4,
    cellHeightPx: 4,
    engineBuildId: 32,
    payloadLength: 4,
    payloadSha256: 32,
  },
  offsets: {
    magic: 0,
    version: 8,
    headerBytes: 10,
    flags: 12,
    throughSeq: 16,
    createdMonoNanos: 24,
    columns: 32,
    rows: 36,
    cellWidthPx: 40,
    cellHeightPx: 44,
    engineBuildId: 48,
    payloadLength: 80,
    payloadSha256: 84,
  },
} as const;
