export const TERMINAL_LIMITS = {
  // The fixed broker array must fit the agent spawn target, orchestrator host, and recovery generations with headroom.
  liveSessionsPerHiveHome: 64,
  authenticatedViewersPerGeneration: 4,
  controlJsonBytesPerFrame: 256 * 1024,
  inputTransactionBytes: 128 * 1024,
  streamChunkBytes: 64 * 1024,
  automatedMessageBytes: 1024 * 1024,
  viewerUnacknowledgedOutputBytes: 8 * 1024 * 1024,
  viewerReattachAfterRebaseMilliseconds: 5_000,
  replayJournalBytesPerGeneration: 64 * 1024 * 1024,
  retainedCheckpoints: 2,
  checkpointBytes: 512 * 1024 * 1024,
  terminalDiskBytesPerHiveHome: 2 * 1024 * 1024 * 1024,
  nonImageCheckpointBytes: 48 * 1024 * 1024,
  terminalCellsPerDimensionMin: 1,
  terminalCellsPerDimensionMax: 1_000,
  terminalActiveCellsMax: 250_000,
  kittyImageDecodedBytesPerGeneration: 16 * 1024 * 1024,
  controlRpcTimeoutMilliseconds: 10_000,
  /** A create is not an RPC that reads a record. It forks a host process, which forks a login `zsh -l -i` — sourcing the user's whole shell profile — which execs a vendor CLI, and the reply waits for all of it. Measured Create latency grows sharply under wide bursts because vendor CLIs start concurrently with the host. The host is competing with. Under one shared 10 s budget the 31-wide burst lost 26 of 31 hosts to create and HELLO timeouts while every create was in fact progressing normally. Bounding "fork a shell and a vendor" with the same number as "read a record" is the same conflation the visibility lease made, one layer down. */
  createRpcTimeoutMilliseconds: 60_000,
  attachGrantTimeoutMilliseconds: 30_000,
  visibilityExpiryMilliseconds: 15_000,
  connectionPingIntervalMilliseconds: 5_000,
  missedPongIntervalsBeforeDetach: 3,
  checkpointOutputIntervalBytes: 2 * 1024 * 1024,
  checkpointIntervalMilliseconds: 30_000,
} as const;
