export const SESSION_PROTOCOL_PATHS = {
  ghosttyVendor: "vendor/ghostty/",
  sessiond: "native/sessiond/",
  sessiondProtocol: "native/sessiond/src/protocol.zig",
  sessiondHost: "native/sessiond/src/session_host.zig",
  sessiondPtyHost: "native/sessiond/src/pty_host.zig",
  sessiondTerminalState: "native/sessiond/src/terminal_state.zig",
  sessiondInputArbiter: "native/sessiond/src/input_arbiter.zig",
  sessiondProcessInspector: "native/sessiond/src/process_inspector.zig",
  daemonSessionHost: "src/daemon/session-host/",
  daemonSessionHostContract: "src/daemon/session-host/session-host-contract.ts",
  daemonSessiondHost: "src/daemon/session-host/sessiond-host.ts",
  schemas: "src/schemas/",
  sessionProtocolSchema: "src/schemas/session-protocol.ts",
  statusEnvelopeSchema: "src/schemas/status-envelope.ts",
  terminalKit: "workspace/Sources/HiveTerminalKit/",
  workspaceCore: "workspace/Sources/WorkspaceCore/",
  statusReducer: "workspace/Sources/WorkspaceCore/WorkspaceStatus.swift",
  fixtures: "workspace/Tests/WorkspaceCoreTests/Fixtures/",
  conformance: "test/session-host-conformance/",
  ghosttyBuildScript: "scripts/native/build-ghosttykit.sh",
} as const;
