import {
  AppliedPayloadSchema,
  AttachGrantPayloadSchema,
  AttachRequestPayloadSchema,
  AutomatedInputMetadataSchema,
  CreateBeginPayloadSchema,
  ErrorPayloadSchema,
  GrantRegisterPayloadSchema,
  HelloPayloadSchema,
  HostAdoptPayloadSchema,
  HostAttachPayloadSchema,
  HostRecordV1Schema,
  HostRegisterPayloadSchema,
  InputSubmitPayloadSchema,
  InspectedPayloadSchema,
  InspectPayloadSchema,
  ListedPayloadSchema,
  ListPayloadSchema,
  PingPongPayloadSchema,
  ResizePayloadSchema,
  TerminatedPayloadSchema,
  TerminatePayloadSchema,
  WelcomePayloadSchema,
} from "./payloads";
import {
  AttachGrantSchema,
  AttachRequestSchema,
  CaptureRequestSchema,
  CaptureResultSchema,
  CreateResultSchema,
  InputReceiptSchema,
  ResizeResultSchema,
  SessionEventSchema,
  SessionInspectionSchema,
  SessionLocatorSchema,
  SessionSpecSchema,
  TerminationRequestSchema,
  TerminationResultSchema,
  TerminalGeometrySchema,
  VisibilityLeaseSchema,
  VisibilityRequestSchema,
} from "./session-protocol-schema";
import {
  TerminalHostAttachRequestSchema,
  TerminalHostAttachResultSchema,
  TerminalHostCheckpointSchema,
  TerminalHostCreateRequestSchema,
  TerminalHostCreateResultSchema,
  TerminalHostEventAcknowledgementRequestSchema,
  TerminalHostEventAcknowledgementSchema,
  TerminalHostResizeReceiptSchema,
  TerminalHostResizeRequestSchema,
  TerminalHostResizeResultSchema,
  TerminalHostSessionInspectionSchema,
  TerminalHostSubscribeRequestSchema,
  TerminalHostSubscribeResultSchema,
  TerminalHostSubscriptionEventSchema,
  TerminalHostTerminationRequestSchema,
  TerminalHostTerminationResultSchema,
} from "./terminal-host";

export const SESSION_WIRE_SCHEMAS = {
  helloPayload: HelloPayloadSchema,
  welcomePayload: WelcomePayloadSchema,
  errorPayload: ErrorPayloadSchema,
  pingPongPayload: PingPongPayloadSchema,
  hostRegisterPayload: HostRegisterPayloadSchema,
  hostAdoptPayload: HostAdoptPayloadSchema,
  grantRegisterPayload: GrantRegisterPayloadSchema,
  hostRecordV1: HostRecordV1Schema,
  createBeginPayload: CreateBeginPayloadSchema,
  listPayload: ListPayloadSchema,
  listedPayload: ListedPayloadSchema,
  inspectPayload: InspectPayloadSchema,
  inspectedPayload: InspectedPayloadSchema,
  terminatePayload: TerminatePayloadSchema,
  terminatedPayload: TerminatedPayloadSchema,
  attachRequestPayload: AttachRequestPayloadSchema,
  attachGrantPayload: AttachGrantPayloadSchema,
  hostAttachPayload: HostAttachPayloadSchema,
  inputSubmitPayload: InputSubmitPayloadSchema,
  resizePayload: ResizePayloadSchema,
  appliedPayload: AppliedPayloadSchema,
  terminalHostCreateRequest: TerminalHostCreateRequestSchema,
  terminalHostCreateResult: TerminalHostCreateResultSchema,
  terminalHostCheckpoint: TerminalHostCheckpointSchema,
  terminalHostSessionInspection: TerminalHostSessionInspectionSchema,
  terminalHostTerminationRequest: TerminalHostTerminationRequestSchema,
  terminalHostTerminationResult: TerminalHostTerminationResultSchema,
  terminalHostResizeRequest: TerminalHostResizeRequestSchema,
  terminalHostResizeReceipt: TerminalHostResizeReceiptSchema,
  terminalHostResizeResult: TerminalHostResizeResultSchema,
  terminalHostAttachRequest: TerminalHostAttachRequestSchema,
  terminalHostAttachResult: TerminalHostAttachResultSchema,
  terminalHostSubscribeRequest: TerminalHostSubscribeRequestSchema,
  terminalHostSubscribeResult: TerminalHostSubscribeResultSchema,
  terminalHostSubscriptionEvent: TerminalHostSubscriptionEventSchema,
  terminalHostEventAcknowledgementRequest:
    TerminalHostEventAcknowledgementRequestSchema,
  terminalHostEventAcknowledgement: TerminalHostEventAcknowledgementSchema,
  sessionLocator: SessionLocatorSchema,
  terminalGeometry: TerminalGeometrySchema,
  sessionSpec: SessionSpecSchema,
  sessionInspection: SessionInspectionSchema,
  createResult: CreateResultSchema,
  captureRequest: CaptureRequestSchema,
  captureResult: CaptureResultSchema,
  attachRequest: AttachRequestSchema,
  attachGrant: AttachGrantSchema,
  visibilityRequest: VisibilityRequestSchema,
  visibilityLease: VisibilityLeaseSchema,
  resizeResult: ResizeResultSchema,
  automatedInputMetadata: AutomatedInputMetadataSchema,
  inputReceipt: InputReceiptSchema,
  terminationRequest: TerminationRequestSchema,
  terminationResult: TerminationResultSchema,
  sessionEvent: SessionEventSchema,
} as const;
