// Shared authorization vocabulary. Minting, verification, and role grants stay
// in the daemon; schemas and services import these names without that engine.
export type { Capability, Role } from "./capability";

export type Action =
  | "status:read"
  | "status:write"
  | "terminal:observe"
  | "quota:read"
  | "quota:write"
  | "token-usage:read"
  | "token-usage:write"
  | "agent:spawn"
  | "agent:kill"
  | "agent:mark-dead"
  | "agent:recover"
  | "settlement:decide"
  | "settlement:execute"
  | "approval:read"
  | "approval:decide"
  | "message:send"
  | "message:ack"
  | "message:read"
  | "inbox:read"
  | "branch:land"
  | "knowledge:read"
  | "run:bootstrap"
  | "node:create"
  | "grant:issue"
  | "task:write"
  | "task:read"
  | "review:write"
  | "artifact:write"
  | "artifact:read"
  | "ownership:transfer"
  | "memory:read"
  | "memory:write"
  | "memory:delete"
  | "event:report"
  | "telemetry:report"
  | "root-token:mint"
  | "autonomy:read"
  | "autonomy:write"
  | "routing-policy:read"
  | "routing-policy:write"
  | "queen-provider:write"
  | "run-control:write"
  | "succession:write"
  | "workspace-visibility:write";
