// Generated by test/session-host-conformance/generate.ts. Do not edit.
// HiveTerminalKit production projection of CHECKPOINT_HEADER (session-protocol.ts).

public enum SessionProtocolGenerated {
    /// HVTCP001 checkpoint envelope (§23 / CHECKPOINT_HEADER).
    public enum Checkpoint {
        public static let magic = "HVTCP001"
        public static let version: UInt16 = 1
        public static let headerBytes = 116
        public static let flags: UInt32 = 0
        public static let engineBuildIdBytes = 32
        public static let payloadSha256Bytes = 32
        public enum Offset {
            public static let magic = 0
            public static let version = 8
            public static let headerBytes = 10
            public static let flags = 12
            public static let throughSeq = 16
            public static let createdMonoNanos = 24
            public static let columns = 32
            public static let rows = 36
            public static let cellWidthPx = 40
            public static let cellHeightPx = 44
            public static let engineBuildId = 48
            public static let payloadLength = 80
            public static let payloadSha256 = 84
        }
        public enum Width {
            public static let magic = 8
            public static let version = 2
            public static let headerBytes = 2
            public static let flags = 4
            public static let throughSeq = 8
            public static let createdMonoNanos = 8
            public static let columns = 4
            public static let rows = 4
            public static let cellWidthPx = 4
            public static let cellHeightPx = 4
            public static let engineBuildId = 32
            public static let payloadLength = 4
            public static let payloadSha256 = 32
        }
    }
}
